"""empty message

Revision ID: 283368b5e18a
Revises: dd41e039bc5c
Create Date: 2025-04-24 23:44:54.167918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283368b5e18a'
down_revision = 'dd41e039bc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
