"""empty message

Revision ID: 28e7c30bb352
Revises: c9ebfecedc78
Create Date: 2025-04-23 20:19:16.439520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e7c30bb352'
down_revision = 'c9ebfecedc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_colones', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('precio_colones')

    # ### end Alembic commands ###
