"""empty message

Revision ID: 7f677b7ffd4a
Revises: 2f143f0c420c
Create Date: 2025-04-23 15:00:22.324072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f677b7ffd4a'
down_revision = '2f143f0c420c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacto')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_salida', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dificultad', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('capacidad_buseta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distancia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lugar_salida', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hora_salida', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('recogemos_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tipoTerreno', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requiere_estadía', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('animales', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('duchas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('banos', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('bastones', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('guantes', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_calzado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('repelente', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bloqueador', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('liquido', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('snacks', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ropa_cambio', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('ropa_cambio')
        batch_op.drop_column('snacks')
        batch_op.drop_column('liquido')
        batch_op.drop_column('bloqueador')
        batch_op.drop_column('repelente')
        batch_op.drop_column('tipo_calzado')
        batch_op.drop_column('guantes')
        batch_op.drop_column('bastones')
        batch_op.drop_column('banos')
        batch_op.drop_column('duchas')
        batch_op.drop_column('animales')
        batch_op.drop_column('requiere_estadía')
        batch_op.drop_column('tipoTerreno')
        batch_op.drop_column('recogemos_en')
        batch_op.drop_column('hora_salida')
        batch_op.drop_column('lugar_salida')
        batch_op.drop_column('distancia')
        batch_op.drop_column('capacidad_total')
        batch_op.drop_column('capacidad_buseta')
        batch_op.drop_column('dificultad')
        batch_op.drop_column('fecha_salida')

    op.create_table('contacto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellido1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellido2', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.VARCHAR(length=20), nullable=True),
    sa.Column('empresa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
