"""empty message

Revision ID: 9b1f5d904511
Revises: 283368b5e18a
Create Date: 2025-05-02 20:16:42.143439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1f5d904511'
down_revision = '283368b5e18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('tarea')
    op.drop_table('post')
    op.drop_table('version')
    op.drop_table('user')
    op.drop_table('contacto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=80), nullable=False),
    sa.Column('apellido1', sa.VARCHAR(length=80), nullable=False),
    sa.Column('apellido2', sa.VARCHAR(length=80), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.VARCHAR(length=20), nullable=True),
    sa.Column('empresa', sa.VARCHAR(length=120), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=80), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('second_last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=200), nullable=True),
    sa.Column('registration_count', sa.INTEGER(), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reset_token_expiration', sa.DATETIME(), nullable=True),
    sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('version',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('detalle1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('detalle2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('detalle3', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('fecha_salida', sa.DATE(), nullable=True),
    sa.Column('dificultad', sa.VARCHAR(length=20), nullable=True),
    sa.Column('capacidad_buseta', sa.INTEGER(), nullable=True),
    sa.Column('capacidad_total', sa.INTEGER(), nullable=True),
    sa.Column('distancia', sa.FLOAT(), nullable=True),
    sa.Column('lugar_salida', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hora_salida', sa.TIME(), nullable=True),
    sa.Column('recogemos_en', sa.TEXT(), nullable=True),
    sa.Column('tipoTerreno', sa.TEXT(), nullable=True),
    sa.Column('requiere_estadía', sa.VARCHAR(length=3), nullable=True),
    sa.Column('animales', sa.VARCHAR(length=3), nullable=True),
    sa.Column('duchas', sa.VARCHAR(length=10), nullable=True),
    sa.Column('banos', sa.VARCHAR(length=3), nullable=True),
    sa.Column('bastones', sa.VARCHAR(length=50), nullable=True),
    sa.Column('guantes', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tipo_calzado', sa.VARCHAR(length=20), nullable=True),
    sa.Column('repelente', sa.VARCHAR(length=10), nullable=True),
    sa.Column('bloqueador', sa.VARCHAR(length=10), nullable=True),
    sa.Column('liquido', sa.VARCHAR(length=10), nullable=True),
    sa.Column('snacks', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ropa_cambio', sa.VARCHAR(length=10), nullable=True),
    sa.Column('precio_colones', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('completada', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
