"""empty message

Revision ID: c211c0f9ca9e
Revises: 28e7c30bb352
Create Date: 2025-04-24 23:10:47.081864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c211c0f9ca9e'
down_revision = '28e7c30bb352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('detalle2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('detalle3', sa.String(length=200), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('detalle3')
        batch_op.drop_column('detalle2')
        batch_op.drop_column('detalle1')

    # ### end Alembic commands ###
