"""empty message

Revision ID: dd41e039bc5c
Revises: c211c0f9ca9e
Create Date: 2025-04-24 23:26:47.400028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd41e039bc5c'
down_revision = 'c211c0f9ca9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('detalle1', sa.String(length=200), nullable=True),
    sa.Column('detalle2', sa.String(length=200), nullable=True),
    sa.Column('detalle3', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_column('detalle3')
        batch_op.drop_column('detalle1')
        batch_op.drop_column('detalle2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle2', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('detalle1', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('detalle3', sa.VARCHAR(length=200), nullable=True))

    op.drop_table('version')
    # ### end Alembic commands ###
