"""empty message

Revision ID: faad59987402
Revises: 9b1f5d904511
Create Date: 2025-05-02 20:23:20.328211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faad59987402'
down_revision = '9b1f5d904511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido1', sa.String(length=80), nullable=False),
    sa.Column('apellido2', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_last_name', sa.String(length=100), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('detalle1', sa.String(length=200), nullable=True),
    sa.Column('detalle2', sa.String(length=200), nullable=True),
    sa.Column('detalle3', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('dificultad', sa.String(length=20), nullable=True),
    sa.Column('capacidad_buseta', sa.Integer(), nullable=True),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('lugar_salida', sa.String(length=100), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('recogemos_en', sa.Text(), nullable=True),
    sa.Column('tipoTerreno', sa.Text(), nullable=True),
    sa.Column('requiere_estadía', sa.String(length=3), nullable=True),
    sa.Column('animales', sa.String(length=3), nullable=True),
    sa.Column('duchas', sa.String(length=10), nullable=True),
    sa.Column('banos', sa.String(length=3), nullable=True),
    sa.Column('bastones', sa.String(length=50), nullable=True),
    sa.Column('guantes', sa.String(length=10), nullable=True),
    sa.Column('tipo_calzado', sa.String(length=20), nullable=True),
    sa.Column('repelente', sa.String(length=10), nullable=True),
    sa.Column('bloqueador', sa.String(length=10), nullable=True),
    sa.Column('liquido', sa.String(length=10), nullable=True),
    sa.Column('snacks', sa.String(length=10), nullable=True),
    sa.Column('ropa_cambio', sa.String(length=10), nullable=True),
    sa.Column('precio_colones', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'post_id', name='unique_participation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participacion')
    op.drop_table('post')
    op.drop_table('video')
    op.drop_table('version')
    op.drop_table('user')
    op.drop_table('tarea')
    op.drop_table('contacto')
    # ### end Alembic commands ###
